# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 18, 35, 41, 687541, tzinfo=utc)),
        ),
    ]
