# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 04:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 13, 4, 53, 36, 836115, tzinfo=utc)),
        ),
    ]
