# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 16:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mines',
            name='mines',
            field=models.CharField(default='1100112929192102932321292139211011232322101129323221000112929100000011211111110011100293910019111399110011239322011100199200019101232100011101910000', max_length=144),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mines',
            field=models.CharField(default='1100112929192102932321292139211011232322101129323221000112929100000011211111110011100293910019111399110011239322011100199200019101232100011101910000', max_length=144),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 10, 16, 25, 47, 934801, tzinfo=utc)),
        ),
    ]
