# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzlepc',
            name='name',
        ),
        migrations.AddField(
            model_name='puzzlepc',
            name='pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puzzlepc',
            name='idno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 28, 7, 20, 31, 123028, tzinfo=utc)),
        ),
    ]
