# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180203_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 16, 36, 44, 32790, tzinfo=utc)),
        ),
    ]
