# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180210_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 10, 16, 30, 56, 654596, tzinfo=utc)),
        ),
    ]
