# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 18:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180210_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 18, 36, 37, 955430, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='time',
            field=models.FloatField(default=7200),
        ),
    ]
