# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180210_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mines',
            name='mines',
            field=models.CharField(default='192100191000129100111111012210000191001910000111123321111000199291191011232322112129921291013931239211019920921101233210110001992000000001392000', max_length=144),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mines',
            field=models.CharField(default='192100191000129100111111012210000191001910000111123321111000199291191011232322112129921291013931239211019920921101233210110001992000000001392000', max_length=144),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 10, 16, 36, 8, 626789, tzinfo=utc)),
        ),
    ]
