# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180210_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='regTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 10, 16, 36, 30, 491590, tzinfo=utc)),
        ),
    ]
